####
GET http://localhost:5000/todos

####
POST http://localhost:5000/todos/add
Content-Type: application/json

{
    "description": "Belajar Kotlin"
}

####
DELETE http://localhost:5000/todos/64804794c82cc42786d4b3a0